nohup: ignoring input
[I 2025-03-25 12:26:21.213 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-03-25 12:26:21.216 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-03-25 12:26:21.220 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-03-25 12:26:21.223 ServerApp] notebook | extension was successfully linked.
[I 2025-03-25 12:26:21.463 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-03-25 12:26:21.476 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-03-25 12:26:21.479 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-03-25 12:26:21.480 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-03-25 12:26:21.481 LabApp] JupyterLab extension loaded from /home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyterlab
[I 2025-03-25 12:26:21.481 LabApp] JupyterLab application directory is /home/gaurav/anaconda3/envs/drone-monitoring/share/jupyter/lab
[I 2025-03-25 12:26:21.481 LabApp] Extension Manager is 'pypi'.
[I 2025-03-25 12:26:21.522 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-03-25 12:26:21.528 ServerApp] notebook | extension was successfully loaded.
[I 2025-03-25 12:26:21.529 ServerApp] Serving notebooks from local directory: /home/gaurav/Drone-Phenology-Monitoring
[I 2025-03-25 12:26:21.529 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-03-25 12:26:21.529 ServerApp] http://localhost:8889/tree?token=9f9d6edb883621bd750f9f278631423d4ca06988aa7c2c00
[I 2025-03-25 12:26:21.529 ServerApp]     http://127.0.0.1:8889/tree?token=9f9d6edb883621bd750f9f278631423d4ca06988aa7c2c00
[I 2025-03-25 12:26:21.529 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-03-25 12:26:21.531 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/gaurav/.local/share/jupyter/runtime/jpserver-692195-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/tree?token=9f9d6edb883621bd750f9f278631423d4ca06988aa7c2c00
        http://127.0.0.1:8889/tree?token=9f9d6edb883621bd750f9f278631423d4ca06988aa7c2c00
[I 2025-03-25 12:26:21.547 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-03-25 12:26:31.053 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:31.055 ServerApp] 403 GET /api/kernels/a9909fb3-a282-45d8-a3e5-36ea1b579163?1742885791047 (@127.0.0.1) 3.30ms referer=None
[W 2025-03-25 12:26:33.107 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.108 ServerApp] 403 GET /api/kernelspecs?1742885793095 (@127.0.0.1) 5.61ms referer=None
[W 2025-03-25 12:26:33.109 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.109 ServerApp] 403 GET /api/kernels?1742885793096 (@127.0.0.1) 5.76ms referer=None
[W 2025-03-25 12:26:33.110 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.110 ServerApp] 403 GET /api/kernels?1742885793098 (@127.0.0.1) 5.62ms referer=None
[W 2025-03-25 12:26:33.110 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.111 ServerApp] 403 GET /api/sessions?1742885793101 (@127.0.0.1) 5.38ms referer=None
[W 2025-03-25 12:26:33.127 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.128 ServerApp] 403 GET /api/kernelspecs?1742885793114 (@127.0.0.1) 1.28ms referer=None
[I 2025-03-25 12:26:33.128 ServerApp] 302 GET / (@127.0.0.1) 1.19ms
[I 2025-03-25 12:26:33.135 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.81ms
[W 2025-03-25 12:26:33.172 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.173 ServerApp] 403 GET /api/kernelspecs?1742885793170 (@127.0.0.1) 1.05ms referer=None
[W 2025-03-25 12:26:33.176 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.177 ServerApp] 403 GET /api/sessions?1742885793174 (@127.0.0.1) 1.46ms referer=None
[W 2025-03-25 12:26:33.178 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.179 ServerApp] 403 GET /api/kernels?1742885793171 (@127.0.0.1) 1.44ms referer=None
[W 2025-03-25 12:26:33.179 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.180 ServerApp] 403 GET /api/kernels?1742885793173 (@127.0.0.1) 1.94ms referer=None
[W 2025-03-25 12:26:33.181 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:26:33.181 ServerApp] 403 GET /api/kernelspecs?1742885793176 (@127.0.0.1) 0.97ms referer=None
[I 2025-03-25 12:26:57.619 ServerApp] 302 GET / (@127.0.0.1) 1.05ms
[I 2025-03-25 12:26:57.629 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.05ms
[I 2025-03-25 12:27:01.298 ServerApp] 302 GET / (@127.0.0.1) 0.51ms
[I 2025-03-25 12:27:01.300 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.52ms
[I 2025-03-25 12:27:07.441 ServerApp] 302 GET / (@127.0.0.1) 0.94ms
[I 2025-03-25 12:27:07.446 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.51ms
[I 2025-03-25 12:27:07.504 ServerApp] Kernel started: 7d768695-6f78-49f5-99e2-50b29be709f6
[I 2025-03-25 12:27:07.924 ServerApp] Connecting to kernel 7d768695-6f78-49f5-99e2-50b29be709f6.
[I 2025-03-25 12:27:08.140 ServerApp] 302 GET / (@127.0.0.1) 0.93ms
[I 2025-03-25 12:27:08.166 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.73ms
[W 2025-03-25 12:27:08.217 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.217 ServerApp] 403 GET /api/kernelspecs?1742885828214 (@127.0.0.1) 1.11ms referer=None
[W 2025-03-25 12:27:08.231 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.232 ServerApp] 403 GET /api/kernels?1742885828215 (@127.0.0.1) 1.43ms referer=None
[W 2025-03-25 12:27:08.232 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.233 ServerApp] 403 GET /api/kernels?1742885828218 (@127.0.0.1) 1.12ms referer=None
[W 2025-03-25 12:27:08.234 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.235 ServerApp] 403 GET /api/sessions?1742885828219 (@127.0.0.1) 1.11ms referer=None
[W 2025-03-25 12:27:08.235 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.235 ServerApp] 403 GET /api/kernelspecs?1742885828227 (@127.0.0.1) 1.58ms referer=None
[I 2025-03-25 12:27:08.244 ServerApp] 302 GET / (@127.0.0.1) 0.63ms
[I 2025-03-25 12:27:08.251 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.85ms
[W 2025-03-25 12:27:08.266 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.266 ServerApp] 403 GET /api/kernelspecs?1742885828263 (@127.0.0.1) 1.16ms referer=None
[W 2025-03-25 12:27:08.275 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.275 ServerApp] 403 GET /api/kernels?1742885828264 (@127.0.0.1) 1.47ms referer=None
[W 2025-03-25 12:27:08.277 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.277 ServerApp] 403 GET /api/kernels?1742885828271 (@127.0.0.1) 1.37ms referer=None
[W 2025-03-25 12:27:08.277 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.278 ServerApp] 403 GET /api/sessions?1742885828272 (@127.0.0.1) 1.75ms referer=None
[W 2025-03-25 12:27:08.280 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 12:27:08.280 ServerApp] 403 GET /api/kernelspecs?1742885828274 (@127.0.0.1) 1.13ms referer=None
[I 2025-03-25 13:25:10.187 ServerApp] Kernel interrupted: 7d768695-6f78-49f5-99e2-50b29be709f6
[I 2025-03-25 13:46:58.200 ServerApp] Kernel interrupted: 7d768695-6f78-49f5-99e2-50b29be709f6
[I 2025-03-25 14:19:19.926 ServerApp] 302 GET / (@127.0.0.1) 0.78ms
[I 2025-03-25 14:19:19.926 ServerApp] 302 GET / (@127.0.0.1) 0.85ms
[I 2025-03-25 14:19:19.933 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.70ms
[I 2025-03-25 14:19:19.935 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.46ms
[W 2025-03-25 14:19:19.989 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:19.990 ServerApp] 403 GET /api/kernelspecs?1742892559986 (@127.0.0.1) 1.25ms referer=None
[W 2025-03-25 14:19:20.096 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.097 ServerApp] 403 GET /api/kernels?1742892559986 (@127.0.0.1) 1.30ms referer=None
[W 2025-03-25 14:19:20.098 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.099 ServerApp] 403 GET /api/kernelspecs?1742892559987 (@127.0.0.1) 1.35ms referer=None
[W 2025-03-25 14:19:20.099 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.099 ServerApp] 403 GET /api/kernels?1742892559987 (@127.0.0.1) 1.80ms referer=None
[W 2025-03-25 14:19:20.106 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.107 ServerApp] 403 GET /api/kernels?1742892560073 (@127.0.0.1) 1.05ms referer=None
[W 2025-03-25 14:19:20.108 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.108 ServerApp] 403 GET /api/sessions?1742892560074 (@127.0.0.1) 1.00ms referer=None
[W 2025-03-25 14:19:20.109 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.109 ServerApp] 403 GET /api/kernels?1742892560075 (@127.0.0.1) 1.54ms referer=None
[W 2025-03-25 14:19:20.110 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.110 ServerApp] 403 GET /api/sessions?1742892560076 (@127.0.0.1) 1.02ms referer=None
[W 2025-03-25 14:19:20.538 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.539 ServerApp] 403 GET /api/kernelspecs?1742892560096 (@127.0.0.1) 1.16ms referer=None
[W 2025-03-25 14:19:20.579 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.579 ServerApp] 403 GET /api/kernelspecs?1742892560106 (@127.0.0.1) 1.23ms referer=None
[I 2025-03-25 14:19:20.581 ServerApp] 302 GET / (@127.0.0.1) 0.51ms
[I 2025-03-25 14:19:20.607 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.69ms
[W 2025-03-25 14:19:20.635 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.636 ServerApp] 403 GET /api/kernelspecs?1742892560633 (@127.0.0.1) 1.09ms referer=None
[W 2025-03-25 14:19:20.652 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.653 ServerApp] 403 GET /api/kernels?1742892560633 (@127.0.0.1) 1.23ms referer=None
[W 2025-03-25 14:19:20.655 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.656 ServerApp] 403 GET /api/kernelspecs?1742892560633 (@127.0.0.1) 2.09ms referer=None
[W 2025-03-25 14:19:20.656 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.656 ServerApp] 403 GET /api/kernels?1742892560634 (@127.0.0.1) 2.73ms referer=None
[W 2025-03-25 14:19:20.657 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.657 ServerApp] 403 GET /api/kernels?1742892560636 (@127.0.0.1) 3.50ms referer=None
[W 2025-03-25 14:19:20.658 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.658 ServerApp] 403 GET /api/sessions?1742892560637 (@127.0.0.1) 4.30ms referer=None
[W 2025-03-25 14:19:20.659 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.659 ServerApp] 403 GET /api/kernels?1742892560637 (@127.0.0.1) 4.85ms referer=None
[W 2025-03-25 14:19:20.660 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.660 ServerApp] 403 GET /api/sessions?1742892560638 (@127.0.0.1) 5.43ms referer=None
[W 2025-03-25 14:19:20.716 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:20.717 ServerApp] 403 GET /api/kernelspecs?1742892560653 (@127.0.0.1) 1.32ms referer=None
[I 2025-03-25 14:19:20.897 ServerApp] 302 GET / (@127.0.0.1) 0.40ms
[I 2025-03-25 14:19:20.899 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.51ms
[I 2025-03-25 14:19:20.922 ServerApp] Connecting to kernel 7d768695-6f78-49f5-99e2-50b29be709f6.
[I 2025-03-25 14:19:21.060 ServerApp] 302 GET / (@127.0.0.1) 0.94ms
[I 2025-03-25 14:19:21.081 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 2.08ms
[W 2025-03-25 14:19:21.095 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.096 ServerApp] 403 GET /api/kernelspecs?1742892561093 (@127.0.0.1) 1.02ms referer=None
[W 2025-03-25 14:19:21.142 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.143 ServerApp] 403 GET /api/kernels?1742892561094 (@127.0.0.1) 1.13ms referer=None
[W 2025-03-25 14:19:21.144 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.144 ServerApp] 403 GET /api/kernels?1742892561095 (@127.0.0.1) 0.99ms referer=None
[W 2025-03-25 14:19:21.144 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.145 ServerApp] 403 GET /api/sessions?1742892561095 (@127.0.0.1) 1.50ms referer=None
[W 2025-03-25 14:19:21.145 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.146 ServerApp] 403 GET /api/kernelspecs?1742892561132 (@127.0.0.1) 0.65ms referer=None
[I 2025-03-25 14:19:21.149 ServerApp] 302 GET / (@127.0.0.1) 0.32ms
[I 2025-03-25 14:19:21.155 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.58ms
[W 2025-03-25 14:19:21.160 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.161 ServerApp] 403 GET /api/kernelspecs?1742892561158 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-25 14:19:21.162 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.162 ServerApp] 403 GET /api/kernels?1742892561159 (@127.0.0.1) 0.87ms referer=None
[W 2025-03-25 14:19:21.166 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.167 ServerApp] 403 GET /api/kernels?1742892561160 (@127.0.0.1) 0.92ms referer=None
[W 2025-03-25 14:19:21.167 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.168 ServerApp] 403 GET /api/sessions?1742892561160 (@127.0.0.1) 0.77ms referer=None
[W 2025-03-25 14:19:21.168 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:21.169 ServerApp] 403 GET /api/kernelspecs?1742892561164 (@127.0.0.1) 0.65ms referer=None
[W 2025-03-25 14:19:22.853 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@127.0.0.1) 5.15ms referer=None
[I 2025-03-25 14:19:22.854 ServerApp] 302 GET / (@127.0.0.1) 0.50ms
[I 2025-03-25 14:19:22.856 ServerApp] 302 GET / (@127.0.0.1) 1.90ms
[I 2025-03-25 14:19:22.872 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.54ms
[I 2025-03-25 14:19:22.876 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.50ms
[W 2025-03-25 14:19:22.888 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.889 ServerApp] 403 GET /api/kernelspecs?1742892562887 (@127.0.0.1) 0.97ms referer=None
[W 2025-03-25 14:19:22.890 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@127.0.0.1) 0.75ms referer=None
[W 2025-03-25 14:19:22.894 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.895 ServerApp] 403 GET /api/kernels?1742892562887 (@127.0.0.1) 0.92ms referer=None
[W 2025-03-25 14:19:22.895 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.896 ServerApp] 403 GET /api/kernels?1742892562890 (@127.0.0.1) 0.68ms referer=None
[W 2025-03-25 14:19:22.905 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.905 ServerApp] 403 GET /api/sessions?1742892562890 (@127.0.0.1) 1.02ms referer=None
[W 2025-03-25 14:19:22.906 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.906 ServerApp] 403 GET /api/kernelspecs?1742892562893 (@127.0.0.1) 0.67ms referer=None
[I 2025-03-25 14:19:22.914 ServerApp] 302 GET / (@127.0.0.1) 0.39ms
[I 2025-03-25 14:19:22.919 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.57ms
[W 2025-03-25 14:19:22.929 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.930 ServerApp] 403 GET /api/kernelspecs?1742892562927 (@127.0.0.1) 1.30ms referer=None
[W 2025-03-25 14:19:22.933 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.933 ServerApp] 403 GET /api/kernels?1742892562928 (@127.0.0.1) 1.00ms referer=None
[W 2025-03-25 14:19:22.934 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.935 ServerApp] 403 GET /api/kernels?1742892562930 (@127.0.0.1) 0.98ms referer=None
[W 2025-03-25 14:19:22.935 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.936 ServerApp] 403 GET /api/sessions?1742892562931 (@127.0.0.1) 1.68ms referer=None
[W 2025-03-25 14:19:22.937 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:19:22.937 ServerApp] 403 GET /api/kernelspecs?1742892562933 (@127.0.0.1) 0.80ms referer=None
[I 2025-03-25 14:33:02.409 ServerApp] 302 GET / (@127.0.0.1) 0.45ms
[I 2025-03-25 14:33:02.409 ServerApp] 302 GET / (@127.0.0.1) 0.26ms
[I 2025-03-25 14:33:02.432 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.74ms
[I 2025-03-25 14:33:02.432 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.46ms
[W 2025-03-25 14:33:02.530 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.531 ServerApp] 403 GET /api/kernelspecs?1742893382528 (@127.0.0.1) 1.09ms referer=None
[W 2025-03-25 14:33:02.557 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.558 ServerApp] 403 GET /api/kernels?1742893382528 (@127.0.0.1) 2.86ms referer=None
[W 2025-03-25 14:33:02.561 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.561 ServerApp] 403 GET /api/kernels?1742893382534 (@127.0.0.1) 1.49ms referer=None
[W 2025-03-25 14:33:02.561 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.562 ServerApp] 403 GET /api/sessions?1742893382534 (@127.0.0.1) 2.07ms referer=None
[W 2025-03-25 14:33:02.564 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.564 ServerApp] 403 GET /api/kernelspecs?1742893382547 (@127.0.0.1) 1.49ms referer=None
[I 2025-03-25 14:33:02.690 ServerApp] 302 GET / (@127.0.0.1) 0.53ms
[I 2025-03-25 14:33:02.700 ServerApp] 302 GET / (@127.0.0.1) 0.42ms
[I 2025-03-25 14:33:02.705 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.66ms
[I 2025-03-25 14:33:02.711 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.63ms
[W 2025-03-25 14:33:02.725 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.726 ServerApp] 403 GET /api/kernelspecs?1742893382723 (@127.0.0.1) 1.23ms referer=None
[W 2025-03-25 14:33:02.746 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.746 ServerApp] 403 GET /api/kernels?1742893382723 (@127.0.0.1) 1.12ms referer=None
[W 2025-03-25 14:33:02.750 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.750 ServerApp] 403 GET /api/kernels?1742893382729 (@127.0.0.1) 1.01ms referer=None
[W 2025-03-25 14:33:02.751 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.751 ServerApp] 403 GET /api/sessions?1742893382730 (@127.0.0.1) 0.83ms referer=None
[W 2025-03-25 14:33:02.754 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:02.755 ServerApp] 403 GET /api/kernelspecs?1742893382743 (@127.0.0.1) 0.98ms referer=None
[I 2025-03-25 14:33:02.835 ServerApp] Connecting to kernel 7d768695-6f78-49f5-99e2-50b29be709f6.
[I 2025-03-25 14:33:03.172 ServerApp] 302 GET / (@127.0.0.1) 0.93ms
[I 2025-03-25 14:33:03.199 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.00ms
[W 2025-03-25 14:33:03.218 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.219 ServerApp] 403 GET /api/kernelspecs?1742893383216 (@127.0.0.1) 1.16ms referer=None
[W 2025-03-25 14:33:03.225 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.225 ServerApp] 403 GET /api/kernels?1742893383216 (@127.0.0.1) 1.10ms referer=None
[W 2025-03-25 14:33:03.226 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.227 ServerApp] 403 GET /api/kernels?1742893383218 (@127.0.0.1) 1.04ms referer=None
[W 2025-03-25 14:33:03.227 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.227 ServerApp] 403 GET /api/sessions?1742893383219 (@127.0.0.1) 1.56ms referer=None
[W 2025-03-25 14:33:03.230 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.231 ServerApp] 403 GET /api/kernelspecs?1742893383222 (@127.0.0.1) 1.00ms referer=None
[I 2025-03-25 14:33:03.247 ServerApp] 302 GET / (@127.0.0.1) 0.51ms
[I 2025-03-25 14:33:03.252 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.60ms
[W 2025-03-25 14:33:03.259 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.260 ServerApp] 403 GET /api/kernelspecs?1742893383257 (@127.0.0.1) 1.11ms referer=None
[W 2025-03-25 14:33:03.263 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.263 ServerApp] 403 GET /api/kernels?1742893383260 (@127.0.0.1) 1.50ms referer=None
[W 2025-03-25 14:33:03.264 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.264 ServerApp] 403 GET /api/sessions?1742893383260 (@127.0.0.1) 2.21ms referer=None
[W 2025-03-25 14:33:03.265 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.266 ServerApp] 403 GET /api/kernels?1742893383258 (@127.0.0.1) 0.91ms referer=None
[W 2025-03-25 14:33:03.269 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 14:33:03.270 ServerApp] 403 GET /api/kernelspecs?1742893383263 (@127.0.0.1) 0.85ms referer=None
[W 2025-03-25 14:33:05.588 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@127.0.0.1) 1.56ms referer=None
[I 2025-03-25 14:33:05.589 ServerApp] 302 GET / (@127.0.0.1) 0.38ms
[I 2025-03-25 14:33:05.599 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.65ms
[W 2025-03-25 14:33:05.606 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@127.0.0.1) 1.39ms referer=None
[I 2025-03-25 17:50:24.821 ServerApp] Starting buffering for 7d768695-6f78-49f5-99e2-50b29be709f6:8af53720-dfd7-41fe-8732-b5baf0d0a456
[I 2025-03-25 23:20:06.996 ServerApp] 302 GET / (@127.0.0.1) 1.71ms
[I 2025-03-25 23:20:06.998 ServerApp] 302 GET / (@127.0.0.1) 0.74ms
[I 2025-03-25 23:20:07.060 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.14ms
[I 2025-03-25 23:20:07.060 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.44ms
[W 2025-03-25 23:20:07.277 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.278 ServerApp] 403 GET /api/kernelspecs?1742925007274 (@127.0.0.1) 1.78ms referer=None
[W 2025-03-25 23:20:07.321 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.322 ServerApp] 403 GET /api/kernels?1742925007275 (@127.0.0.1) 1.52ms referer=None
[W 2025-03-25 23:20:07.324 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.324 ServerApp] 403 GET /api/kernels?1742925007296 (@127.0.0.1) 0.93ms referer=None
[W 2025-03-25 23:20:07.325 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.325 ServerApp] 403 GET /api/sessions?1742925007303 (@127.0.0.1) 0.98ms referer=None
[W 2025-03-25 23:20:07.328 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.328 ServerApp] 403 GET /api/kernelspecs?1742925007316 (@127.0.0.1) 0.93ms referer=None
[I 2025-03-25 23:20:07.344 ServerApp] 302 GET / (@127.0.0.1) 0.47ms
[I 2025-03-25 23:20:07.355 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.81ms
[W 2025-03-25 23:20:07.374 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.375 ServerApp] 403 GET /api/kernelspecs?1742925007371 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-25 23:20:07.386 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.387 ServerApp] 403 GET /api/kernels?1742925007372 (@127.0.0.1) 1.25ms referer=None
[W 2025-03-25 23:20:07.388 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.388 ServerApp] 403 GET /api/kernels?1742925007376 (@127.0.0.1) 1.29ms referer=None
[W 2025-03-25 23:20:07.389 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.389 ServerApp] 403 GET /api/sessions?1742925007377 (@127.0.0.1) 1.81ms referer=None
[W 2025-03-25 23:20:07.390 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.391 ServerApp] 403 GET /api/kernelspecs?1742925007383 (@127.0.0.1) 0.97ms referer=None
[I 2025-03-25 23:20:07.819 ServerApp] 302 GET / (@127.0.0.1) 0.77ms
[I 2025-03-25 23:20:07.846 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.78ms
[W 2025-03-25 23:20:07.862 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:07.863 ServerApp] 403 GET /api/kernelspecs?1742925007860 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-25 23:20:08.004 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.005 ServerApp] 403 GET /api/kernels?1742925007861 (@127.0.0.1) 1.58ms referer=None
[W 2025-03-25 23:20:08.006 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.006 ServerApp] 403 GET /api/kernels?1742925007864 (@127.0.0.1) 1.21ms referer=None
[W 2025-03-25 23:20:08.006 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.007 ServerApp] 403 GET /api/sessions?1742925007865 (@127.0.0.1) 1.67ms referer=None
[W 2025-03-25 23:20:08.060 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.061 ServerApp] 403 GET /api/kernelspecs?1742925007915 (@127.0.0.1) 1.57ms referer=None
[I 2025-03-25 23:20:08.070 ServerApp] 302 GET / (@127.0.0.1) 0.62ms
[I 2025-03-25 23:20:08.075 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.67ms
[W 2025-03-25 23:20:08.086 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.087 ServerApp] 403 GET /api/kernelspecs?1742925008083 (@127.0.0.1) 1.71ms referer=None
[W 2025-03-25 23:20:08.094 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.094 ServerApp] 403 GET /api/kernelspecs?1742925008091 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-25 23:20:08.095 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.095 ServerApp] 403 GET /api/kernels?1742925008084 (@127.0.0.1) 0.96ms referer=None
[W 2025-03-25 23:20:08.096 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.096 ServerApp] 403 GET /api/kernels?1742925008087 (@127.0.0.1) 1.15ms referer=None
[W 2025-03-25 23:20:08.096 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:08.096 ServerApp] 403 GET /api/sessions?1742925008088 (@127.0.0.1) 1.44ms referer=None
[I 2025-03-25 23:20:09.644 ServerApp] 302 GET / (@127.0.0.1) 0.89ms
[I 2025-03-25 23:20:09.670 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.11ms
[W 2025-03-25 23:20:09.739 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.740 ServerApp] 403 GET /api/kernelspecs?1742925009735 (@127.0.0.1) 1.52ms referer=None
[W 2025-03-25 23:20:09.757 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.759 ServerApp] 403 GET /api/kernels?1742925009736 (@127.0.0.1) 1.84ms referer=None
[W 2025-03-25 23:20:09.759 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.760 ServerApp] 403 GET /api/kernels?1742925009738 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-25 23:20:09.761 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.762 ServerApp] 403 GET /api/sessions?1742925009739 (@127.0.0.1) 1.32ms referer=None
[W 2025-03-25 23:20:09.762 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.763 ServerApp] 403 GET /api/kernelspecs?1742925009750 (@127.0.0.1) 1.63ms referer=None
[I 2025-03-25 23:20:09.900 ServerApp] 302 GET / (@127.0.0.1) 0.62ms
[I 2025-03-25 23:20:09.912 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.09ms
[W 2025-03-25 23:20:09.926 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.926 ServerApp] 403 GET /api/kernelspecs?1742925009923 (@127.0.0.1) 1.41ms referer=None
[W 2025-03-25 23:20:09.933 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.933 ServerApp] 403 GET /api/kernels?1742925009924 (@127.0.0.1) 1.81ms referer=None
[W 2025-03-25 23:20:09.934 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.934 ServerApp] 403 GET /api/kernelspecs?1742925009929 (@127.0.0.1) 2.46ms referer=None
[W 2025-03-25 23:20:09.935 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.935 ServerApp] 403 GET /api/kernels?1742925009925 (@127.0.0.1) 1.48ms referer=None
[W 2025-03-25 23:20:09.935 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-25 23:20:09.936 ServerApp] 403 GET /api/sessions?1742925009926 (@127.0.0.1) 0.70ms referer=None
[I 2025-03-27 20:41:03.430 ServerApp] 302 GET / (@127.0.0.1) 0.90ms
[I 2025-03-27 20:41:03.435 ServerApp] 302 GET / (@127.0.0.1) 0.58ms
[I 2025-03-27 20:41:03.466 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.16ms
[I 2025-03-27 20:41:03.467 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.52ms
[W 2025-03-27 20:41:04.060 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.060 ServerApp] 403 GET /api/kernelspecs?1743088264054 (@127.0.0.1) 1.45ms referer=None
[W 2025-03-27 20:41:04.267 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.267 ServerApp] 403 GET /api/kernels?1743088264055 (@127.0.0.1) 3.46ms referer=None
[W 2025-03-27 20:41:04.269 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.270 ServerApp] 403 GET /api/kernels?1743088264101 (@127.0.0.1) 4.38ms referer=None
[W 2025-03-27 20:41:04.270 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.270 ServerApp] 403 GET /api/sessions?1743088264102 (@127.0.0.1) 4.65ms referer=None
[W 2025-03-27 20:41:04.328 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.329 ServerApp] 403 GET /api/kernelspecs?1743088264242 (@127.0.0.1) 1.09ms referer=None
[I 2025-03-27 20:41:04.355 ServerApp] 302 GET / (@127.0.0.1) 1.77ms
[I 2025-03-27 20:41:04.396 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 1.09ms
[W 2025-03-27 20:41:04.421 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.421 ServerApp] 403 GET /api/kernelspecs?1743088264418 (@127.0.0.1) 1.18ms referer=None
[W 2025-03-27 20:41:04.456 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.456 ServerApp] 403 GET /api/kernels?1743088264419 (@127.0.0.1) 1.33ms referer=None
[W 2025-03-27 20:41:04.457 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.458 ServerApp] 403 GET /api/kernels?1743088264421 (@127.0.0.1) 1.33ms referer=None
[W 2025-03-27 20:41:04.458 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.459 ServerApp] 403 GET /api/sessions?1743088264422 (@127.0.0.1) 1.73ms referer=None
[W 2025-03-27 20:41:04.459 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.460 ServerApp] 403 GET /api/kernelspecs?1743088264428 (@127.0.0.1) 0.72ms referer=None
[I 2025-03-27 20:41:04.645 ServerApp] 302 GET / (@127.0.0.1) 1.15ms
[I 2025-03-27 20:41:04.676 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.90ms
[W 2025-03-27 20:41:04.689 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.689 ServerApp] 403 GET /api/kernelspecs?1743088264687 (@127.0.0.1) 1.05ms referer=None
[W 2025-03-27 20:41:04.706 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.707 ServerApp] 403 GET /api/kernels?1743088264687 (@127.0.0.1) 1.42ms referer=None
[W 2025-03-27 20:41:04.708 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.708 ServerApp] 403 GET /api/kernels?1743088264690 (@127.0.0.1) 1.21ms referer=None
[W 2025-03-27 20:41:04.709 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.709 ServerApp] 403 GET /api/sessions?1743088264690 (@127.0.0.1) 1.53ms referer=None
[W 2025-03-27 20:41:04.709 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.710 ServerApp] 403 GET /api/kernelspecs?1743088264698 (@127.0.0.1) 0.69ms referer=None
[I 2025-03-27 20:41:04.717 ServerApp] 302 GET / (@127.0.0.1) 0.56ms
[I 2025-03-27 20:41:04.721 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.75ms
[W 2025-03-27 20:41:04.732 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.733 ServerApp] 403 GET /api/kernelspecs?1743088264730 (@127.0.0.1) 1.14ms referer=None
[W 2025-03-27 20:41:04.745 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.745 ServerApp] 403 GET /api/kernels?1743088264730 (@127.0.0.1) 1.09ms referer=None
[W 2025-03-27 20:41:04.746 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.746 ServerApp] 403 GET /api/kernels?1743088264732 (@127.0.0.1) 0.68ms referer=None
[W 2025-03-27 20:41:04.747 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.747 ServerApp] 403 GET /api/sessions?1743088264733 (@127.0.0.1) 0.75ms referer=None
[W 2025-03-27 20:41:04.747 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 20:41:04.748 ServerApp] 403 GET /api/kernelspecs?1743088264740 (@127.0.0.1) 1.05ms referer=None
[I 2025-03-27 23:11:50.556 ServerApp] 302 GET / (@127.0.0.1) 1.47ms
[I 2025-03-27 23:11:50.607 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.79ms
[W 2025-03-27 23:11:50.713 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.714 ServerApp] 403 GET /api/kernelspecs?1743097310710 (@127.0.0.1) 1.24ms referer=None
[W 2025-03-27 23:11:50.729 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.729 ServerApp] 403 GET /api/kernels?1743097310711 (@127.0.0.1) 1.53ms referer=None
[W 2025-03-27 23:11:50.730 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.730 ServerApp] 403 GET /api/kernels?1743097310716 (@127.0.0.1) 1.80ms referer=None
[W 2025-03-27 23:11:50.730 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.730 ServerApp] 403 GET /api/sessions?1743097310717 (@127.0.0.1) 2.10ms referer=None
[W 2025-03-27 23:11:50.731 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.731 ServerApp] 403 GET /api/kernelspecs?1743097310723 (@127.0.0.1) 0.67ms referer=None
[I 2025-03-27 23:11:50.745 ServerApp] 302 GET / (@127.0.0.1) 0.75ms
[I 2025-03-27 23:11:50.753 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.87ms
[W 2025-03-27 23:11:50.763 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.764 ServerApp] 403 GET /api/kernelspecs?1743097310761 (@127.0.0.1) 1.17ms referer=None
[W 2025-03-27 23:11:50.768 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.769 ServerApp] 403 GET /api/kernels?1743097310761 (@127.0.0.1) 1.25ms referer=None
[W 2025-03-27 23:11:50.770 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.770 ServerApp] 403 GET /api/kernels?1743097310763 (@127.0.0.1) 0.89ms referer=None
[W 2025-03-27 23:11:50.770 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.771 ServerApp] 403 GET /api/sessions?1743097310764 (@127.0.0.1) 1.08ms referer=None
[W 2025-03-27 23:11:50.774 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-27 23:11:50.775 ServerApp] 403 GET /api/kernelspecs?1743097310768 (@127.0.0.1) 0.94ms referer=None
[I 2025-03-28 03:29:55.624 ServerApp] 302 GET / (@127.0.0.1) 0.70ms
[I 2025-03-28 03:29:55.625 ServerApp] 302 GET / (@127.0.0.1) 0.57ms
[I 2025-03-28 03:29:55.751 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.80ms
[I 2025-03-28 03:29:55.751 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.45ms
[W 2025-03-28 03:29:55.861 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:55.861 ServerApp] 403 GET /api/kernelspecs?1743112795859 (@127.0.0.1) 1.02ms referer=None
[W 2025-03-28 03:29:55.878 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:55.878 ServerApp] 403 GET /api/kernels?1743112795859 (@127.0.0.1) 0.73ms referer=None
[W 2025-03-28 03:29:55.880 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:55.880 ServerApp] 403 GET /api/kernels?1743112795862 (@127.0.0.1) 1.48ms referer=None
[W 2025-03-28 03:29:55.880 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:55.880 ServerApp] 403 GET /api/sessions?1743112795862 (@127.0.0.1) 1.74ms referer=None
[W 2025-03-28 03:29:55.893 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:55.894 ServerApp] 403 GET /api/kernelspecs?1743112795871 (@127.0.0.1) 1.19ms referer=None
[I 2025-03-28 03:29:55.905 ServerApp] 302 GET / (@127.0.0.1) 0.42ms
[I 2025-03-28 03:29:55.924 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.67ms
[W 2025-03-28 03:29:56.035 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:56.036 ServerApp] 403 GET /api/kernelspecs?1743112796033 (@127.0.0.1) 1.14ms referer=None
[W 2025-03-28 03:29:56.057 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:56.057 ServerApp] 403 GET /api/kernels?1743112796034 (@127.0.0.1) 1.11ms referer=None
[W 2025-03-28 03:29:56.058 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:56.058 ServerApp] 403 GET /api/kernels?1743112796046 (@127.0.0.1) 0.83ms referer=None
[W 2025-03-28 03:29:56.058 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:56.059 ServerApp] 403 GET /api/sessions?1743112796047 (@127.0.0.1) 1.10ms referer=None
[W 2025-03-28 03:29:56.059 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:29:56.060 ServerApp] 403 GET /api/kernelspecs?1743112796054 (@127.0.0.1) 0.57ms referer=None
[I 2025-03-28 03:30:01.330 ServerApp] 302 GET / (@127.0.0.1) 6.97ms
[I 2025-03-28 03:30:01.342 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.56ms
[W 2025-03-28 03:30:01.350 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.351 ServerApp] 403 GET /api/kernelspecs?1743112801348 (@127.0.0.1) 0.81ms referer=None
[W 2025-03-28 03:30:01.353 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.353 ServerApp] 403 GET /api/kernels?1743112801349 (@127.0.0.1) 0.65ms referer=None
[W 2025-03-28 03:30:01.354 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.354 ServerApp] 403 GET /api/kernels?1743112801351 (@127.0.0.1) 0.73ms referer=None
[W 2025-03-28 03:30:01.354 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.355 ServerApp] 403 GET /api/sessions?1743112801351 (@127.0.0.1) 1.01ms referer=None
[W 2025-03-28 03:30:01.361 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.361 ServerApp] 403 GET /api/kernelspecs?1743112801353 (@127.0.0.1) 0.96ms referer=None
[I 2025-03-28 03:30:01.362 ServerApp] 302 GET / (@127.0.0.1) 0.34ms
[I 2025-03-28 03:30:01.368 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.63ms
[W 2025-03-28 03:30:01.376 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.376 ServerApp] 403 GET /api/kernelspecs?1743112801373 (@127.0.0.1) 1.56ms referer=None
[W 2025-03-28 03:30:01.377 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.377 ServerApp] 403 GET /api/kernels?1743112801374 (@127.0.0.1) 1.83ms referer=None
[W 2025-03-28 03:30:01.390 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.391 ServerApp] 403 GET /api/kernels?1743112801380 (@127.0.0.1) 0.95ms referer=None
[W 2025-03-28 03:30:01.391 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.391 ServerApp] 403 GET /api/sessions?1743112801381 (@127.0.0.1) 1.23ms referer=None
[W 2025-03-28 03:30:01.392 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 03:30:01.392 ServerApp] 403 GET /api/kernelspecs?1743112801388 (@127.0.0.1) 0.68ms referer=None
[I 2025-03-28 10:17:30.709 ServerApp] 302 GET / (@127.0.0.1) 0.71ms
[I 2025-03-28 10:17:30.710 ServerApp] 302 GET / (@127.0.0.1) 0.39ms
[I 2025-03-28 10:17:30.718 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.63ms
[I 2025-03-28 10:17:30.719 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.33ms
[W 2025-03-28 10:17:30.810 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.810 ServerApp] 403 GET /api/kernelspecs?1743137250807 (@127.0.0.1) 1.07ms referer=None
[W 2025-03-28 10:17:30.859 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.859 ServerApp] 403 GET /api/kernels?1743137250808 (@127.0.0.1) 1.24ms referer=None
[W 2025-03-28 10:17:30.864 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.864 ServerApp] 403 GET /api/kernels?1743137250816 (@127.0.0.1) 4.25ms referer=None
[W 2025-03-28 10:17:30.864 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.865 ServerApp] 403 GET /api/sessions?1743137250817 (@127.0.0.1) 4.50ms referer=None
[W 2025-03-28 10:17:30.868 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.868 ServerApp] 403 GET /api/kernelspecs?1743137250836 (@127.0.0.1) 0.70ms referer=None
[I 2025-03-28 10:17:30.920 ServerApp] 302 GET / (@127.0.0.1) 0.53ms
[I 2025-03-28 10:17:30.938 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.75ms
[W 2025-03-28 10:17:30.954 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:30.954 ServerApp] 403 GET /api/kernelspecs?1743137250951 (@127.0.0.1) 1.07ms referer=None
[W 2025-03-28 10:17:31.046 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:31.047 ServerApp] 403 GET /api/kernels?1743137250952 (@127.0.0.1) 1.47ms referer=None
[W 2025-03-28 10:17:31.048 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:31.048 ServerApp] 403 GET /api/kernels?1743137250954 (@127.0.0.1) 1.28ms referer=None
[W 2025-03-28 10:17:31.049 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:31.049 ServerApp] 403 GET /api/sessions?1743137250954 (@127.0.0.1) 1.67ms referer=None
[W 2025-03-28 10:17:31.086 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:31.087 ServerApp] 403 GET /api/kernelspecs?1743137250961 (@127.0.0.1) 2.17ms referer=None
[I 2025-03-28 10:17:36.273 ServerApp] 302 GET / (@127.0.0.1) 4.25ms
[I 2025-03-28 10:17:36.285 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.51ms
[W 2025-03-28 10:17:36.298 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.298 ServerApp] 403 GET /api/kernelspecs?1743137256295 (@127.0.0.1) 0.79ms referer=None
[W 2025-03-28 10:17:36.308 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.308 ServerApp] 403 GET /api/kernels?1743137256296 (@127.0.0.1) 0.89ms referer=None
[W 2025-03-28 10:17:36.309 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.309 ServerApp] 403 GET /api/kernels?1743137256302 (@127.0.0.1) 0.89ms referer=None
[W 2025-03-28 10:17:36.309 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.310 ServerApp] 403 GET /api/sessions?1743137256303 (@127.0.0.1) 1.13ms referer=None
[W 2025-03-28 10:17:36.310 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.310 ServerApp] 403 GET /api/kernelspecs?1743137256304 (@127.0.0.1) 1.38ms referer=None
[I 2025-03-28 10:17:36.318 ServerApp] 302 GET / (@127.0.0.1) 0.79ms
[I 2025-03-28 10:17:36.320 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.45ms
[W 2025-03-28 10:17:36.326 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.327 ServerApp] 403 GET /api/kernelspecs?1743137256325 (@127.0.0.1) 0.91ms referer=None
[W 2025-03-28 10:17:36.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.331 ServerApp] 403 GET /api/kernels?1743137256325 (@127.0.0.1) 1.40ms referer=None
[W 2025-03-28 10:17:36.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.332 ServerApp] 403 GET /api/kernels?1743137256327 (@127.0.0.1) 1.67ms referer=None
[W 2025-03-28 10:17:36.332 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.332 ServerApp] 403 GET /api/sessions?1743137256328 (@127.0.0.1) 1.88ms referer=None
[W 2025-03-28 10:17:36.344 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/home/gaurav/anaconda3/envs/drone-monitoring/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-03-28 10:17:36.345 ServerApp] 403 GET /api/kernelspecs?1743137256335 (@127.0.0.1) 1.12ms referer=None
